[package]
name = "dialoguemaker/shaking-effect"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
dialogue-content-fitter = "dialoguemaker/dialogue-content-fitter@0.1.0"
effect = "dialoguemaker/effect@0.1.0"
effect-types = "dialoguemaker/effect-types@0.1.0"
react = "jsdotlua/react@17.2.1"